version: "3.8"
networks:
  redis-net:
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - redis-net
  rki-api:
    container_name: rki-covid-api
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    # image: docker.pkg.github.com/marlon360/rki-covid-api/rki-server:latest
    ports:
      - "8080:3000"
    depends_on:
      - updater
      - redis
    environment:
      - REDISHOST=redis
    volumes:
      - ./src/cache:/usr/src/app/dist/cache
      - dataStore:/usr/src/app/dataStore:ro
    networks:
      - redis-net
  updater:
    container_name: updater
    build:
      context: ./updater/
      dockerfile: ./Dockerfile
    volumes:
      - dataStore:/usr/src/app/dataStore
volumes:
  dataStore:
