version: "3.8"
networks:
  redis-net:
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - redis-net
  rki-api:
    container_name: rki-covid-api
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    # image: docker.pkg.github.com/marlon360/rki-covid-api/rki-server:latest
    ports:
      - "8080:3000"
    depends_on:
      - fix-incidence
      - redis
    environment:
      - REDISHOST=redis
    volumes:
      - ./src/cache:/usr/src/app/dist/cache
      - Fallzahlen:/usr/src/app/Fallzahlen:ro
    networks:
      - redis-net
  fix-incidence:
    container_name: cronjob
    build:
      context: ./cronjob/
      dockerfile: ./Dockerfile
    volumes:
      - Fallzahlen:/usr/src/app/Fallzahlen
volumes:
  Fallzahlen:
