version: "3.8"
networks:
  redis-net:
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - redis-net
  rki-api:
    container_name: rki-covid-api
    image: marlon360/rki-covid-server:v2
    ports:
      - "8080:3000"
    depends_on:
      - updater
      - redis
    environment:
      - REDISHOST=redis
    networks:
      - redis-net
    volumes:
      - dataStore:/usr/src/app/dataStore:ro
  updater:
    container_name: updater
    build:
      context: ./updater/
      dockerfile: ./Dockerfile
    volumes:
      - dataStore:/usr/src/app/dataStore
volumes:
  dataStore:
